"""
Utility functions for fly-stocker-v2.

This module contains:
    - ID cleaning and parsing utilities
    - Collection classification and sorting
    - Keyword processing functions
    - FlyBase TSV loading functions
"""

import gzip
import re
from glob import glob
from pathlib import Path
from typing import Dict, List, Optional, Union

import pandas as pd



###############################################################################
# ID Cleaning and Parsing Utilities
###############################################################################

def clean_id(val) -> str:
    """
    Clean an ID value (PMID, PMCID, stock number, etc.) to a normalized string.
    
    Handles:
    - None/NaN values -> ""
    - Float-like strings ending in ".0" -> removes suffix
    - "nan" strings -> ""
    - Whitespace trimming
    
    Args:
        val: Any value that might be an ID
    
    Returns:
        Cleaned string, or empty string if invalid
    """
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str.endswith('.0'):
        val_str = val_str[:-2]
    return val_str if val_str.lower() != "nan" else ""


def is_valid_id(val) -> bool:
    """Check if a value represents a valid ID (not empty/NaN)."""
    return bool(clean_id(val))


def parse_semicolon_list(values_str: str) -> List[str]:
    """Parse a semicolon-separated string into a list of cleaned values."""
    if pd.isna(values_str) or not str(values_str).strip():
        return []
    return [v.strip() for v in str(values_str).split(';') if v.strip()]


def join_semicolon_list(values: List[str], sort: bool = False) -> str:
    """Join a list of values into a semicolon-separated string."""
    if not values:
        return ""
    return '; '.join(sorted(set(values)) if sort else values)


def filter_semicolon_values(
    values_str: str,
    exclude_set: set,
    value_mapping: Dict[str, str] = None
) -> str:
    """
    Filter semicolon-separated values, excluding those in exclude_set.
    
    Args:
        values_str: Semicolon-separated string of values
        exclude_set: Set of values to exclude
        value_mapping: Optional dict to map input values to output values
    
    Returns:
        Filtered semicolon-separated string
    """
    values = parse_semicolon_list(values_str)
    if value_mapping:
        filtered = [value_mapping.get(v, v) for v in values if v not in exclude_set and value_mapping.get(v)]
    else:
        filtered = [v for v in values if v not in exclude_set]
    return join_semicolon_list(filtered)


###############################################################################
# Keyword Processing Functions
###############################################################################

def generate_keyword_column_name(keywords: List[str]) -> str:
    """
    Generate the column name for keyword matching based on the keywords.
    
    Args:
        keywords: List of keywords
    
    Returns:
        Column name like "sleep OR circadian in title/ abstract of publication?"
    """
    if not keywords:
        return "Keyword in title/ abstract of publication?"
    return f"{' OR '.join(keywords)} in title/ abstract of publication?"


def find_keyword_column(df: pd.DataFrame) -> Optional[str]:
    """
    Find the GPT-derived 'PMID of <keywords> references that showed stocks
    functional validity' column.

    This column is produced by the GPT functional-validation step and is
    **not** the same as the title/abstract keyword-hit column.  Used by
    ``get_gpt_derived_columns`` to tag GPT-derived data.

    Returns the column name if found, None otherwise.
    """
    pattern = re.compile(r"^PMID of .+ references that showed stocks functional validity$")
    for col in df.columns:
        if pattern.match(str(col)):
            return col
    return None


def find_keyword_title_abstract_column(df: pd.DataFrame) -> Optional[str]:
    """
    Find the title/abstract keyword-hit boolean column produced by
    ``pipeline_references``.

    The column is named like
    ``"sleep OR circadian in title/ abstract of publication?"``
    (generated by :func:`generate_keyword_column_name`).

    Returns the column name if found, None otherwise.
    """
    pattern = re.compile(r"in title/ abstract of publication\?$")
    for col in df.columns:
        if pattern.search(str(col)):
            return col
    return None


def extract_keywords_from_title_abstract_column(col_name: str) -> List[str]:
    """
    Extract keywords from a title/abstract column name like
    ``"sleep OR circadian in title/ abstract of publication?"``.

    Returns list of keywords (e.g., ``['sleep', 'circadian']``).
    """
    match = re.match(
        r"^(.+?)\s+in title/ abstract of publication\?$", col_name
    )
    if not match:
        return []

    keywords_str = match.group(1)
    # "Keyword" is the placeholder when no keywords were supplied
    if keywords_str == "Keyword":
        return []
    keywords = [kw.strip() for kw in keywords_str.split(" OR ")]
    return keywords


def extract_keywords_from_column(col_name: str) -> List[str]:
    """
    Extract keywords from a column name.

    Supports both the title/abstract column
    (``"sleep OR circadian in title/ abstract of publication?"``) and the
    legacy GPT-derived column
    (``"PMID of sleep OR circadian references that showed stocks functional
    validity"``).

    Returns list of keywords (e.g., ``['sleep', 'circadian']``).
    """
    # Try title/abstract pattern first (preferred)
    result = extract_keywords_from_title_abstract_column(col_name)
    if result:
        return result

    # Legacy GPT-derived pattern
    match = re.match(r"^PMID of (.+) references that showed stocks functional validity$", col_name)
    if not match:
        return []

    keywords_str = match.group(1)
    keywords = [kw.strip() for kw in keywords_str.split(" OR ")]
    return keywords


def has_keyword_validation(value) -> bool:
    """
    Check if a stock has validation in keyword-matching references.
    
    Returns True if the 'PMID of <kw> references that showed stocks functional validity'
    column has content.
    """
    if pd.isna(value):
        return False
    return bool(str(value).strip())


###############################################################################
# GPT-Derived / Experimental Column Handling
###############################################################################

# Static names of columns whose values come from GPT / functional validation
GPT_DERIVED_COLUMNS_STATIC = frozenset({
    "Functional Validity (by reference)?",
    "Functionally Valid Stock?",
    "phenotypes_observed",
    "validation_rationale",
})

# Prefix used to mark experimental/GPT-derived cell values
EXPERIMENTAL_PREFIX = "[EXPERIMENTAL] "


def get_gpt_derived_columns(df: pd.DataFrame) -> List[str]:
    """
    Return list of GPT-derived column names present in a DataFrame.

    Includes both static column names and the dynamic
    'PMID of <keywords> references that showed stocks functional validity' column.
    """
    cols = [c for c in GPT_DERIVED_COLUMNS_STATIC if c in df.columns]
    # Dynamic keyword validation column
    kw_col = find_keyword_column(df)
    if kw_col and kw_col in df.columns:
        cols.append(kw_col)
    return cols


def apply_experimental_prefix(df: pd.DataFrame) -> pd.DataFrame:
    """
    Return a copy of *df* with '[EXPERIMENTAL] ' prefixed to the **column
    headers** of GPT-derived columns.  Cell values are left unchanged.
    Avoids double-prefixing if the header already starts with the prefix.
    """
    gpt_cols = get_gpt_derived_columns(df)
    if not gpt_cols:
        return df

    df = df.copy()
    rename_map = {}
    for col in gpt_cols:
        if not str(col).startswith(EXPERIMENTAL_PREFIX):
            rename_map[col] = f"{EXPERIMENTAL_PREFIX}{col}"
    if rename_map:
        df = df.rename(columns=rename_map)
    return df


def load_keywords(filepath: Path) -> List[str]:
    """
    Load keywords from a text file (one keyword/phrase per line).
    
    Args:
        filepath: Path to the keywords file
    
    Returns:
        List of lowercase keywords
    """
    keywords = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            kw = line.strip().lower()
            if kw and not kw.startswith('#'):  # Skip empty lines and comments
                keywords.append(kw)
    return keywords


###############################################################################
# Collection Classification
###############################################################################

def get_stock_collection(collection_value: str) -> str:
    """
    Normalize and return the stock collection value from the 'collection' column.
    
    Args:
        collection_value: The value from the 'collection' column
        
    Returns:
        Normalized collection name, or 'Unknown' if not available
    """
    if pd.isna(collection_value) or not str(collection_value).strip():
        return "Unknown"
    return str(collection_value).strip()


def classify_stocks_collection_in_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add a _stock_collection column based on the 'collection' column in the DataFrame.
    
    The input Excel file must have a 'collection' column that specifies the stock
    center/source (e.g., 'Bloomington', 'Kyoto', 'VDRC', etc.).
    
    Args:
        df: DataFrame with stock data (must have 'collection' column)
        
    Returns:
        DataFrame with _stock_collection column added
    """
    df = df.copy()
    
    # Look for the collection column (case-insensitive)
    collection_col = None
    for col in df.columns:
        if col.lower() == 'collection':
            collection_col = col
            break
    
    if collection_col is None:
        raise ValueError(
            "Input Excel file must have a 'collection' column specifying the stock center "
            "(e.g., 'Bloomington', 'Kyoto', 'VDRC'). Column not found."
        )
    
    # Check for custom stocks and override collection
    def get_collection_with_custom_check(row):
        is_custom = row.get("is_custom_stock", False)
        stock_num = str(row.get("stock_number", "")).upper()
        if is_custom or stock_num == "CUSTOM":
            return "Custom Lab Generated"
        return get_stock_collection(row.get(collection_col, ""))
    
    df["_stock_collection"] = df.apply(get_collection_with_custom_check, axis=1)
    return df


def get_collection_sort_key(collection: str, collection_stock_counts: Dict[str, int]) -> tuple:
    """
    Generate a sort key for collections.
    
    Priority:
    1. Bloomington (0)
    2. Custom Lab Generated (1)
    3. Others (2, sorted by descending stock count)
    
    Args:
        collection: Collection name
        collection_stock_counts: Dict mapping collection -> stock count
    
    Returns:
        Tuple (priority, count_sort_key)
    """
    collection_lower = str(collection).lower().strip()
    stock_count = collection_stock_counts.get(collection, 0)
    
    if "bloomington" in collection_lower or collection_lower == "bdsc":
        return (0, 0)
    elif "custom lab generated" in collection_lower:
        return (1, 0)
    else:
        return (2, -stock_count)


###############################################################################
# FlyBase TSV Loading Functions
###############################################################################

def find_latest_tsv(directory: Path, pattern: str) -> Path:
    """
    Find the latest TSV file matching a pattern in a directory.
    Prefers .gz files, falls back to .tsv if no .gz exists.
    """
    # Try gzipped first
    gz_files = sorted(glob(str(directory / f"{pattern}*.tsv.gz")), reverse=True)
    if gz_files:
        return Path(gz_files[0])
    
    # Fall back to uncompressed
    tsv_files = sorted(glob(str(directory / f"{pattern}*.tsv")), reverse=True)
    if tsv_files:
        return Path(tsv_files[0])
    
    raise FileNotFoundError(f"No TSV file matching '{pattern}' found in {directory}")


def load_flybase_tsv(filepath: Union[str, Path], **kwargs) -> pd.DataFrame:
    """
    Load a FlyBase TSV file, handling various comment/header formats.
    
    FlyBase TSV files have varying formats:
      - Some have ## metadata comments, then #header, then data
      - Some have multiple # comment lines before #header with tabs
      - Some have NO # prefix on headers (plain column names on line 1)
      - Some have #---- separator lines after the header
    
    This function detects and handles all these cases.
    Supports both .tsv and .tsv.gz files.
    """
    filepath = Path(filepath)
    
    # Determine opener based on file extension
    if filepath.suffix == '.gz' or str(filepath).endswith('.tsv.gz'):
        opener = lambda f: gzip.open(f, 'rt', encoding='utf-8')
    else:
        opener = lambda f: open(f, 'r', encoding='utf-8')
    
    # First pass: find the header line and count rows to skip
    skip_rows = 0
    header_line = None
    use_custom_header = False
    header_found = False
    
    with opener(filepath) as f:
        for i, line in enumerate(f):
            stripped = line.strip()
            
            # Skip empty lines
            if not stripped:
                skip_rows = i + 1
                continue
            
            # Check if this is a comment line (to skip)
            is_comment = False
            
            if stripped.startswith('##'):
                is_comment = True
            elif stripped.startswith('#-'):
                is_comment = True
            elif stripped.startswith('# '):
                is_comment = True
            elif stripped.startswith('#') and '\t' not in stripped:
                is_comment = True
            
            if is_comment:
                skip_rows = i + 1
                continue
            
            if header_found:
                skip_rows = i
                break
            
            # This line might be the header
            if stripped.startswith('#'):
                header_content = stripped[1:]
                cols = header_content.split('\t')
                col_names = [c.strip() for c in cols if c.strip()]
                
                if len(col_names) >= 2:
                    header_line = col_names
                    use_custom_header = True
                    header_found = True
                    skip_rows = i + 1
                    continue
                else:
                    skip_rows = i + 1
                    continue
            else:
                cols = stripped.split('\t')
                first_field = cols[0].strip() if cols else ""
                if first_field.startswith('FB') and len(first_field) > 4:
                    break
                else:
                    break
    
    # Read the file
    if use_custom_header and header_line:
        df = pd.read_csv(
            filepath,
            sep='\t',
            skiprows=skip_rows,
            names=header_line,
            low_memory=False,
            on_bad_lines='warn',
            **kwargs
        )
    else:
        df = pd.read_csv(
            filepath,
            sep='\t',
            skiprows=skip_rows,
            low_memory=False,
            on_bad_lines='warn',
            **kwargs
        )
    
    return df
